"""empty message

Revision ID: 09703a7824e4
Revises: 0f6aa81edcb8
Create Date: 2021-10-19 16:51:08.102726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09703a7824e4'
down_revision = '0f6aa81edcb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipoId', sa.String(length=30), nullable=True),
    sa.Column('numeroId', sa.Integer(), nullable=True),
    sa.Column('nombres', sa.String(length=100), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nombreUsuario', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=20), nullable=True),
    sa.Column('estado', sa.Boolean(), nullable=True),
    sa.Column('idTipoUsuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idTipoUsuario'], ['tipo_usuario.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numeroId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuario')
    op.drop_table('tipo_usuario')
    # ### end Alembic commands ###
